nodeweb:
  build: .
  container_name: "nodeweb"
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"

nodedb:
  container_name: "nodedb"
  image: mysql

